let info = {
  alys: 10,
  brandon: 5,
  fidelia: 8,
  //marcel: 10,
  megan: 5,
  sejo: 5,
  shalaka: 10,
  teoma: 4,
  thembi: 4,
  ximena: 6
}
let txt = {
  alys: ["Across latitudes and how to build a new, with a new collaborative work Across latitudes and languages", "beginning With care and obsessions", "and letting go of vocabulary constantly", "possibility", "The unforeseen", "Okay blurry", "How to place", "Now relations", "And our differences", "As the as the guiding resource", "So the work", "is more documentation", "Of process", "Then the", "Then the outcome", "The outcome", "would be", "Like", "respectful relationships across", "by artists from different", "geopolitical situations", "and And language that hadn't been seen in advance", "Let the restrictions that house", "house abandon our", "The conventions of outcome focused research proposal to instead focus on"],
  brandon: [" "],
  fidelia: ["i've been thinking about fans a lot in the last couple of days and paper fans, specifically, which is why i'm Holding This now weeks and folds and the lose and all that fun goodness.yeah there's like that to lose quote that's like i'm forever unfolding between two folds and if to perceive as to if to unfold, then I am forever unfolding between the phone or something like that it's from."],
  marcel: ["I think I want to talk more about Fidelia yes project it stuck with me so much because.", "they chose to work on a project mainly about.", "sort of digital communication tools and techniques.", " And Just to to focus on these moments of of in between, on these interstices on these moments of waiting, as someone else is typing.", "An a message or a message to me and and they sort of have these like three dots popping up on my phone.", "And what i'm doing now is the negative, of the three dots that I cut out before for fidelia'ss project i'm going to glue on to this bracelet so what this is is it's actually a a sort of bracelet that we present waiting, as in digital communication tools.", "For the slippers we're gonna.", "be really nice to reuse this bracelet for.", "which it just be. Like. flip flop style.Like the simple slipper ever.", "Again, it could be, it could be could be a slippers slippers slippers of waiting with just three dots", " so I think i'm just gonna be inspired by this aesthetics", " that we have started and attached three dots will depend."],
  megan: [" I was taking the moment where you're describing to articulate some Heads on the worms that are crawling from my project to Nina and so as project.", "They already had tails, but they needed little pet shapes so they got that and then looking at these materials, while you were saying to propose a new one i'm just i'm so going back to how I has done some pretty stark contrast between like.", "Organic materials and what is maybe.", "Intellectual construct or.it 's not even so much mechanical.", "i'm so like these notions of how.", "Biological matter crosses into system like network things that aren 't aren't even in physical form but you know this like human desire to crawl into the matrix and the matrix ease and and roll around so i 'm like", " Okay, I want to invite Nina and Selma to come roll around in police reports with me. And then we invite other people to do the same and we see what they feel like and we see what.We see what's inside there that isn 't being shown in these box frameworks that gets spit out after they're cleaned up oh i 've also started talking a lot about fuzzy data which.Outside the sciences, is just a really humorous term", "And i'm picturing bodies like rolling around and crawling through like the threads "],
  sejo: ["Another project to do as I was saying", "like connecting different like these beautiful rooms and different possible paths between them", "some of them like maybe you could go from one to another direct directly on my way to in order to get to another", "you have to take a longer path"],
  shalaka: [""],
  teoma: ["I think these spaces are often quite abstract or i'm often thinking about disciplinary spaces, which are defined differently than geographic spaces.", "and, You know, part of what.", "This.", "intersection of these spaces", "I think", "And this, you know these virtual spaces this online.", "Is I mean part of what it brings is this yes magic arrival.", "In the shared space, but.", "Without a lot of contextual information about how.", "everyone's arriving and I think this is.", "Well, maybe always the case, I don't think it's a bad thing.", "But it.   It leaves me really with this question about.", "How we arrive in a space.", "And that sort of arrived will being.", "Part of the event itself and the collaboration itself and the performance itself and the exchange itself."],
  thembi: ["Very surface body and technology, one of the person that I think I found the more connection in the first phase was in a can they can be tell i'm not sure how to pronounce but it's found a placeholder group we were on the same NICO a's in the and we have some extent obviously started coalition together ", "it will change now the rain is done I can tend to nature."],
  ximena: ["i've been dreaming quite a lot with a particular set of colors of sunset so let's say this is a kind of more.", "If there's ethereal.", "So, said, the third area.", "This actually could be the tree.", "This is a physical object that is in location, this is fixing location could be the tree.", "So this is a part of this is this this isn't a location.", "This is something in the imagination.", "This is something that we cannot see.", "And this is the thing that we need to wear this is a wearable, this is a wearable.", "And all these are people who are using that and, of course, I am, you said that I need to do something different, probably i'm doing something similar is quite difficult to to go out but let's say that."]
}